### PR TITLE
Fixed 10ms page load slowdown.

### PR DESCRIPTION
**Pull request by Intelli**

### CODE REVIEW

**Comment by specious** [comment]
According to the [official documentation](https://developer.chrome.com/extensions/content_scripts#run_at), valid values for `"run_at"` are:

- `"document_start"`
- `"document_end"`
- `"document_idle"`

The default is `"document_idle"`.

> In the case of "document_start", the files are injected after any files from css, but before any other DOM is constructed or any other script is run.
> [...]
> In the case of "document_idle", the browser chooses a time to inject scripts between "document_end" and immediately after the window.onload event fires. The exact moment of injection depends on how complex the document is and how long it is taking to load, and is optimized for page load speed. 

I used the extension with both `"document_start"` and the default and it seems to work fine either way.

How did you measure the speed difference?

**Comment by kav2k** [comment]
At the very least, using "document_start" will allow the extension to gather data much, much faster (before the page is actually loaded and parsed).

**Comment by kav2k** [comment]
Oh nevermind, I misread what actually happens in the content script. This will not speed it up, since the background waits for tab status `"complete"`.

**Comment by kav2k** [comment]
Okay, I'm sorry for my previous comments, I completely misunderstood that this pull request deletes, and not adds, this line.

I measured the performance impact of this script using Chrome profiling tools. It came out at 4.2ms.

It's debatable if such a difference is significant enough.

However, this patch introduces a potential race condition between `onMessage` being registered and `complete` firing for the tab in the background (triggering `sendMessage`). In short, the tab might miss the message if it only starts listening after `"document_idle"`.

**Comment by rauchg** [comment]
Thanks for the analysys @kav2k

**Comment by Intelli** [comment]
I was measuring the speed difference by looking at the "Load" time in the Chrome developer tools, and comparing it with/without the extension, as well as comparing it to my fork with the code change. This was being performed on a single image.

As well, this change doesn't cause a race condition. Per the documentation specious quoted, using the "document_idle" value still injects scripts *before* "document_end". With this change, the "DOMContentLoaded" event listener still fires 100% of the time. 

I'm still seeing this page load slowdown occurring in Chrome 55 beta.

**Comment by kav2k** [comment]
@NextGenDan The documentation explicitly says that `"document_idle"` occurs some time after `DOMContentLoaded`. `"document_end"`, however, fires immediately at `DOMContentLoaded`.

I can provide further details from more in-depth experience: it occurs at `DOMContentLoaded` + 200ms or `window.onload`, whichever is faster.

So, no. `document_end` is guaranteed to be no later than `document_idle`.

----

At the point this patch was introduced, the extension behaved significantly differently: the content script was listening for an initial message from the background script, generated on `tabs.onUpdated`. This would introduce a race condition: the listener did not wait until page load (which is, at worst, when `document_end` code executes for a slow-loading page) to send the message, which could therefore be missed.

Since then, in #31, this was reversed: the content script is the one sending the message, so the race condition criticism no longer applies. So now this patch is safe in comparison to when it was introduced.

**Comment by kav2k** [comment]
Sorry, that should be #30 for the logic reversal.

**Comment by kav2k** [comment]
Correction: the logic was reversed in #33. Sorry for the confusion, it's still early morning for me.

**Comment by kav2k** [comment]
As I said, with the changed content script logic this patch now should be safe; more profiling is required as to measure the impact on different machines.

The remaining question here, basically, is this: _is the slowdown cure worth having the indicator be incorrect/"empty" during the page loading time?_

**Comment by Intelli** [comment]
Honestly, I never even noticed a difference in how long the indicator takes to display. Comparing it side by side, I see the difference. However, it seems unlikely that anyone would have a workflow which requires seeing the indicator prior to a page being loaded.

**Pull request closed without merging**
